// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameApplicationTag = "application_tag"

// ApplicationTag mapped from table <application_tag>
type ApplicationTag struct {
	ID            int64        `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	ApplicationID int64        `gorm:"column:application_id;type:bigint;not null;uniqueIndex:application_tag_application_id_dict_platform_id_key,priority:1" json:"application_id"`
	TagID         int64        `gorm:"column:tag_id;type:bigint;not null;uniqueIndex:application_tag_application_id_dict_platform_id_key,priority:2" json:"tag_id"`
	CreatedTs     *time.Time   `gorm:"column:created_ts;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP" json:"created_ts"`
	Application   *Application `gorm:"foreignKey:ApplicationID" json:"application"`
	Tag           *Tag         `gorm:"foreignKey:TagID" json:"tag"`
}

// TableName ApplicationTag's table name
func (*ApplicationTag) TableName() string {
	return TableNameApplicationTag
}
