// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAudit = "audit"

// Audit mapped from table <audit>
type Audit struct {
	ID        *string    `gorm:"column:id;type:uuid;primaryKey;default:gen_random_uuid()" json:"id"`
	CreateTs  *time.Time `gorm:"column:create_ts;type:timestamp with time zone;not null;index:audit_create_ts_key,priority:1;default:CURRENT_TIMESTAMP" json:"create_ts"`
	Username  string     `gorm:"column:username;type:character varying;not null" json:"username"`
	IP        *string    `gorm:"column:ip;type:cidr" json:"ip"`
	RequestID string     `gorm:"column:request_id;type:character varying;not null" json:"request_id"`
	Message   string     `gorm:"column:message;type:text;not null" json:"message"`
	Meta      *string    `gorm:"column:meta;type:jsonb" json:"meta"`
}

// TableName Audit's table name
func (*Audit) TableName() string {
	return TableNameAudit
}
