// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDictPlatform = "dict_platform"

// DictPlatform mapped from table <dict_platform>
type DictPlatform struct {
	ID          int16      `gorm:"column:id;type:smallint;primaryKey" json:"id"`
	Name        string     `gorm:"column:name;type:character varying;not null" json:"name"`
	DisplayName *string    `gorm:"column:display_name;type:character varying" json:"display_name"`
	CreatedTs   *time.Time `gorm:"column:created_ts;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP" json:"created_ts"`
	ModifiedTs  *time.Time `gorm:"column:modified_ts;type:timestamp with time zone;not null;autoUpdateTime" json:"modified_ts"`
	DeletedTs   *time.Time `gorm:"column:deleted_ts;type:timestamp with time zone" json:"deleted_ts"`
}

// TableName DictPlatform's table name
func (*DictPlatform) TableName() string {
	return TableNameDictPlatform
}
