// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTag = "tag"

// Tag mapped from table <tag>
type Tag struct {
	ID         int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	Name       string     `gorm:"column:name;type:character varying;not null" json:"name"`
	CreatedTs  *time.Time `gorm:"column:created_ts;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP" json:"created_ts"`
	ModifiedTs *time.Time `gorm:"column:modified_ts;type:timestamp with time zone;not null;default:CURRENT_TIMESTAMP" json:"modified_ts"`
	DeletedTs  *time.Time `gorm:"column:deleted_ts;type:timestamp with time zone" json:"deleted_ts"`
}

// TableName Tag's table name
func (*Tag) TableName() string {
	return TableNameTag
}
