//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type ApplicationTag struct {
	ID            int64 `sql:"primary_key"`
	ApplicationID int64
	TagID         int64
	CreatedTs     time.Time
}
