//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Application struct {
	ID             int64 `sql:"primary_key"`
	DictPlatformID int16
	Name           string
	DisplayName    *string
	CreatedTs      time.Time
	ModifiedTs     time.Time
	DeletedTs      *time.Time
	SomeFlg        bool
	SomeDouble1    float64
	SomeDouble2    *float64
	SomeJSON       string
}
