//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type DictPlatform struct {
	ID          int16 `sql:"primary_key"`
	Name        string
	DisplayName *string
	CreatedTs   time.Time
	ModifiedTs  time.Time
	DeletedTs   *time.Time
}
